--------------------------------------------------------
--  Arquivo criado - Domingo-Janeiro-10-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CONTATOS"."CLIENTE" 
   (	"CPF" VARCHAR2(14 BYTE), 
	"NOME" VARCHAR2(150 BYTE), 
	"IDADE" NUMBER, 
	"SEXO" VARCHAR2(14 BYTE), 
	"INTERESSES" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CONTATOS"."CLIENTE"."CPF" IS 'CPF do cliente.';
   COMMENT ON COLUMN "CONTATOS"."CLIENTE"."NOME" IS 'Nome do cliente';
   COMMENT ON COLUMN "CONTATOS"."CLIENTE"."IDADE" IS 'Idade do cliente';
   COMMENT ON COLUMN "CONTATOS"."CLIENTE"."SEXO" IS 'Sexo do cliente';
   COMMENT ON COLUMN "CONTATOS"."CLIENTE"."INTERESSES" IS 'Interesses do cliente';
--------------------------------------------------------
--  DDL for Index PK_C_C
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTATOS"."PK_C_C" ON "CONTATOS"."CLIENTE" ("CPF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CONTATOS"."CLIENTE" ADD CONSTRAINT "PK_C_C" PRIMARY KEY ("CPF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTATOS"."CLIENTE" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "CONTATOS"."CLIENTE" MODIFY ("IDADE" NOT NULL ENABLE);
  ALTER TABLE "CONTATOS"."CLIENTE" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "CONTATOS"."CLIENTE" MODIFY ("CPF" NOT NULL ENABLE);

--------------------------------------------------------
--  Arquivo criado - Domingo-Janeiro-10-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LISTA_CONTATO
--------------------------------------------------------

  CREATE TABLE "CONTATOS"."LISTA_CONTATO" 
   (	"CPF" VARCHAR2(14 BYTE), 
	"TP_CONTATO" NUMBER, 
	"CONTATO" VARCHAR2(150 BYTE), 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LC_I
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTATOS"."PK_LC_I" ON "CONTATOS"."LISTA_CONTATO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table LISTA_CONTATO
--------------------------------------------------------

  ALTER TABLE "CONTATOS"."LISTA_CONTATO" ADD CONSTRAINT "PK_LC_I" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTATOS"."LISTA_CONTATO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "CONTATOS"."LISTA_CONTATO" MODIFY ("CONTATO" NOT NULL ENABLE);
  ALTER TABLE "CONTATOS"."LISTA_CONTATO" MODIFY ("TP_CONTATO" NOT NULL ENABLE);
  ALTER TABLE "CONTATOS"."LISTA_CONTATO" MODIFY ("CPF" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table LISTA_CONTATO
--------------------------------------------------------

  ALTER TABLE "CONTATOS"."LISTA_CONTATO" ADD CONSTRAINT "FK_CC_CC" FOREIGN KEY ("CPF")
	  REFERENCES "CONTATOS"."CLIENTE" ("CPF") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CONTATOS"."LISTA_CONTATO" ADD CONSTRAINT "FK_CTC_TCTC" FOREIGN KEY ("TP_CONTATO")
	  REFERENCES "CONTATOS"."TIPO_CONTATO" ("TP_CONTATO") ENABLE;

--------------------------------------------------------
--  Arquivo criado - Domingo-Janeiro-10-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPO_CONTATO
--------------------------------------------------------

  CREATE TABLE "CONTATOS"."TIPO_CONTATO" 
   (	"TP_CONTATO" NUMBER, 
	"DS_CONTATO" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CONTATOS"."TIPO_CONTATO"."TP_CONTATO" IS 'Id do tipo de contato.';
   COMMENT ON COLUMN "CONTATOS"."TIPO_CONTATO"."DS_CONTATO" IS 'Descrição do tipo de contato.';
--------------------------------------------------------
--  DDL for Index PK_TC_TC
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTATOS"."PK_TC_TC" ON "CONTATOS"."TIPO_CONTATO" ("TP_CONTATO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPO_CONTATO
--------------------------------------------------------

  ALTER TABLE "CONTATOS"."TIPO_CONTATO" ADD CONSTRAINT "PK_TC_TC" PRIMARY KEY ("TP_CONTATO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTATOS"."TIPO_CONTATO" MODIFY ("DS_CONTATO" NOT NULL ENABLE);
  ALTER TABLE "CONTATOS"."TIPO_CONTATO" MODIFY ("TP_CONTATO" NOT NULL ENABLE);

--------------------------------------------------------
--  Arquivo criado - Domingo-Janeiro-10-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence S_LISTA_CONTATO
--------------------------------------------------------

   CREATE SEQUENCE  "CONTATOS"."S_LISTA_CONTATO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;

--------------------------------------------------------
--  Arquivo criado - Domingo-Janeiro-10-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence S_TIPO_CONTATO
--------------------------------------------------------

   CREATE SEQUENCE  "CONTATOS"."S_TIPO_CONTATO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
